export const hanjaLevel8 = [
  { hanja: "校", title: "학교 교" },
  { hanja: "敎", title: "가르칠 교" },
  { hanja: "九", title: "아홉 구" },
  { hanja: "國", title: "나라 국" },
  { hanja: "軍", title: "군사 군" },
  { hanja: "金", title: "쇠-성 금-김" },
  { hanja: "南", title: "남녘 남" },
  { hanja: "女", title: "계집 녀" },
  { hanja: "年", title: "해 년" },
  { hanja: "大", title: "큰 대" },
  { hanja: "東", title: "동녘 동" },
  { hanja: "六", title: "여섯 륙" },
  { hanja: "萬", title: "일만 만" },
  { hanja: "母", title: "어미 모" },
  { hanja: "木", title: "나무 목" },
  { hanja: "門", title: "문 문" },
  { hanja: "民", title: "백성 민" },
  { hanja: "白", title: "흰 백" },
  { hanja: "父", title: "아비 부" },
  { hanja: "北", title: "북녘 북" },
  { hanja: "四", title: "넉 사" },
  { hanja: "山", title: "메 산" },
  { hanja: "三", title: "석 삼" },
  { hanja: "生", title: "날 생" },
  { hanja: "西", title: "서녘 서" },
  { hanja: "先", title: "먼저 선" },
  { hanja: "小", title: "작을 소" },
  { hanja: "水", title: "물 수" },
  { hanja: "室", title: "집 실" },
  { hanja: "十", title: "열 십" },
  { hanja: "五", title: "다섯 오" },
  { hanja: "王", title: "임금 왕" },
  { hanja: "外", title: "바깥 외" },
  { hanja: "月", title: "달 월" },
  { hanja: "二", title: "두 이" },
  { hanja: "人", title: "사람 인" },
  { hanja: "一", title: "한 일" },
  { hanja: "日", title: "날 일" },
  { hanja: "長", title: "긴 장" },
  { hanja: "弟", title: "아우 제" },
  { hanja: "中", title: "가운데 중" },
  { hanja: "靑", title: "푸를 청" },
  { hanja: "寸", title: "마디 촌" },
  { hanja: "七", title: "일곱 칠" },
  { hanja: "土", title: "흙 토" },
  { hanja: "八", title: "여덟 팔" },
  { hanja: "學", title: "배울 학" },
  { hanja: "韓", title: "한국 한" },
  { hanja: "兄", title: "형 형" },
  { hanja: "火", title: "불 화" },
];

export const hanjaLevel7II = [
  { hanja: "家", title: "집 가" },
  { hanja: "間", title: "사이 간" },
  { hanja: "江", title: "강 강" },
  { hanja: "車", title: "수레 거-차" },
  { hanja: "工", title: "장인 공" },
  { hanja: "空", title: "빌 공" },
  { hanja: "氣", title: "기운 기" },
  { hanja: "記", title: "기록할 기" },
  { hanja: "男", title: "사내 남" },
  { hanja: "內", title: "안 내" },
  { hanja: "農", title: "농사 농" },
  { hanja: "答", title: "대답 답" },
  { hanja: "道", title: "길 도" },
  { hanja: "動", title: "움직일 동" },
  { hanja: "力", title: "힘 력" },
  { hanja: "立", title: "설 립" },
  { hanja: "每", title: "매양 매" },
  { hanja: "名", title: "이름 명" },
  { hanja: "物", title: "물건 물" },
  { hanja: "方", title: "모 방" },
  { hanja: "不", title: "아닐 불" },
  { hanja: "事", title: "일 사" },
  { hanja: "上", title: "윗 상" },
  { hanja: "姓", title: "성 성" },
  { hanja: "世", title: "인간 세" },
  { hanja: "手", title: "손 수 " },
  { hanja: "時", title: "때 시" },
  { hanja: "市", title: "저자 시" },
  { hanja: "食", title: "밥-먹을 식" },
  { hanja: "安", title: "편안 안" },
  { hanja: "午", title: "낮 오" },
  { hanja: "右", title: "오른 우" },
  { hanja: "子", title: "아들 자" },
  { hanja: "自", title: "스스로 자" },
  { hanja: "場", title: "마당 장" },
  { hanja: "電", title: "번개 전" },
  { hanja: "前", title: "앞 전" },
  { hanja: "全", title: "온전 전" },
  { hanja: "正", title: "바를 정" },
  { hanja: "足", title: "발 족" },
  { hanja: "左", title: "왼 좌" },
  { hanja: "直", title: "곧을 직" },
  { hanja: "平", title: "평평할 평" },
  { hanja: "下", title: "아래 하" },
  { hanja: "漢", title: "한수-하나라 한" },
  { hanja: "海", title: "바다 해" },
  { hanja: "話", title: "말씀 화" },
  { hanja: "活", title: "살 활" },
  { hanja: "孝", title: "효도 효" },
  { hanja: "後", title: "뒤 후" },
];

export const hanjaLevel7 = [
  {hanja : "歌", title: "노래 가"},
  {hanja : "口", title: "입 구"},
  {hanja : "旗", title: "기 기"},
  {hanja : "同", title: "한가지 동"},
  {hanja : "洞", title: "골 동 / 밝을 통"},
  {hanja : "冬", title: "겨울 동"},
  {hanja : "登", title: "오를 등"},
  {hanja : "來", title: "올 래"},
  {hanja : "老", title: "늙을 로"},
  {hanja : "里", title: "마을 리"},
  {hanja : "林", title: "수풀 림"},
  {hanja : "面", title: "낯 면"},
  {hanja : "命", title: "목숨 명"},
  {hanja : "文", title: "글월 문"},
  {hanja : "問", title: "물을 문"},
  {hanja : "百", title: "일백 백"},
  {hanja : "夫", title: "지아비 부"},
  {hanja : "算", title: "셈 산"},
  {hanja : "色", title: "빛 색"},
  {hanja : "夕", title: "저녁 석"},
  {hanja : "少", title: "적을 소"},
  {hanja : "所", title: "바 소"},
  {hanja : "數", title: "셈 수"},
  {hanja : "植", title: "심을 식"},
  {hanja : "心", title: "마음 심"},
  {hanja : "語", title: "말씀 어"},
  {hanja : "然", title: "그럴 연"},
  {hanja : "有", title: "있을 유"},
  {hanja : "育", title: "기를 육"},
  {hanja : "邑", title: "고을 읍"},
  {hanja : "入", title: "들 입"},
  {hanja : "字", title: "글자 자"},
  {hanja : "祖", title: "할아비 조"},
  {hanja : "住", title: "살 주"},
  {hanja : "主", title: "임금/주인 주"},
  {hanja : "重", title: "무거울 중"},
  {hanja : "紙", title: "종이 지"},
  {hanja : "地", title: "땅 지"},
  {hanja : "千", title: "일천 천"},
  {hanja : "天", title: "하늘 천"},
  {hanja : "川", title: "내 천"},
  {hanja : "草", title: "풀 초"},
  {hanja : "村", title: "마을 촌"},
  {hanja : "秋", title: "가을 추"},
  {hanja : "春", title: "봄 춘"},
  {hanja : "出", title: "날 출"},
  {hanja : "便", title: "편한 편 / 똥오줌 변"},
  {hanja : "夏", title: "여름 하"},
  {hanja : "花", title: "꽃 화"},
  {hanja : "休", title: "쉴 휴"},
]